FROM python:3.12-slim
ENV WEEWX_ROOT=/home/weewx/weewx-data
ENV HOME=/home/weewx
ENV TZ=America/New_York
ENV PATH=/usr/bin:$PATH
ENV LANG=en_US.UTF-8

ARG BUILD_DEPS="wget unzip git libffi-dev libjpeg-dev gcc g++ build-essential zlib1g-dev"

RUN apt-get update \
  && apt-get install --no-install-recommends -y \
      $BUILD_DEPS \
      tzdata \
      rsync \
      vim \
      openssh-client \
      openssl \
      locales \
  && rm -rf /var/lib/apt/lists/* \
  && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
  && echo "en_GB.UTF-8 UTF-8" >> /etc/locale.gen \
  && echo "de_DE.UTF-8 UTF-8" >> /etc/locale.gen \
  && echo "nl_NL.UTF-8 UTF-8" >> /etc/locale.gen \
  && locale-gen \
  && addgroup weewx \
  && useradd -m -g weewx weewx \
  && chown -R weewx:weewx /home/weewx \
  && chmod -R 755 /home/weewx

USER weewx

RUN python3 -m venv /home/weewx/weewx-venv \
  && chmod -R 755 /home/weewx

RUN . /home/weewx/weewx-venv/bin/activate \
  && python3 -m pip install --no-cache-dir \
      numpy \
      pandas \
      skyfield \
      paho-mqtt \
      db-sqlite3 \
      requests

RUN . /home/weewx/weewx-venv/bin/activate \
  && pip install weewx==5.3.1 \
  && pip uninstall -y ephem \
  && weectl station create --no-prompt

USER root
RUN apt-get purge -y $BUILD_DEPS \
  && apt-get autoremove -y \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER weewx
